### ISSUE TITLE
Explicitly set padding on the UL in the dropdown to avoid conflicts

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/compounds#75]
The dropdown menu utilizes a `ul` to list the dropdown options. If the dropdown is located within an element that contains other `ul`s it is likely that it will inherit some left padding (for example, if you `@extend .pe-list` for lists within the container).

It would be nice if the dropdown applied a `padding-left: 0;` style to the contained `ul` so this wouldn't have to be overridden manually.

**Comment by parkerpearson** [comment]
Looks like some margins are easily overridden as well.

**Comment by parkerpearson** [comment]
And the `li`s are getting an unnecessary margin.

**Comment by mhomolak** [comment]
There is an active PR overhauling Dropdown. 
https://github.com/Pearson-Higher-Ed/compounds/pull/74
