### ISSUE TITLE
How do I turn off selectable items in the dropdown?

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/compounds#84]
Can't figure out from the documentation how to have a new dropdown menu that does not show the checkmark icon nor allow selected items in the menu.

**Comment by mhomolak** [comment]
From Hung - The selectable items are sent down using props.

**Comment by StommePoes** [comment]
Um, can we have an example for the docs?

**Comment by parkerpearson** [comment]
Yes, an example would be good, I tried playing with props and couldn't figure out how it worked.

**Comment by mhomolak** [comment]
"I can't figure something out" usually isn't a use for these issues, by the way.

**Comment by StommePoes** [comment]
We'd rather have Parker ask once and we add it to docs than have the question repeated by every Angular/whatever dev who comes along wondering the same thing though.
Usually our READMEs for other components have example code for initialising the element and usually the example will have some example options passed in then. Even then, App-Header users didn't realise they could set the link text/URLs in the header. After Collections asked how to get rid of the URL to console, we added it to the docs and now we can point all future "but all the links go to Console!" comments to the README.

**Comment by mhomolak** [comment]
The point is this can be something addressed over hipchat.

**Comment by parkerpearson** [comment]
Sounds fine, as long as the documentation is updated as well

**Comment by mhomolak** [comment]
I'll give Hung a heads up.  He said he would look into the Safari & FF thing today.
