### ISSUE TITLE
Dropdown icon only has button background

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/compounds#85]
Looks like the icon only dropdown trigger has a default button background, this should be removed: 
![screen shot 2017-09-12 at 4 59 36 pm](https://user-images.githubusercontent.com/13319923/30352166-d2504946-97db-11e7-9358-baeca9390e47.png)
![screen shot 2017-09-12 at 5 00 10 pm](https://user-images.githubusercontent.com/13319923/30352184-ddf54044-97db-11e7-94af-b1c6efc282a0.png)

**Comment by mhomolak** [comment]
I'll remove the button background in a pr for something else I already have open.
